<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\HiringPlatform.Domain\HiringPlatform.Domain.csproj" />
    <ProjectReference Include="..\HiringPlatform.ServiceDefaults\HiringPlatform.ServiceDefaults.csproj" />
    <Compile Include="..\HiringPlatform.Api\ApiConstants.cs" Link="ApiConstants.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Minio" Version="7.0.0" />
  </ItemGroup>
</Project>
